<a href="https://colab.research.google.com/github/yuliiakovall/firstrepository/blob/main/Hw_10_4_apply%2C_groupby%2C_pivot_table.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [16]:
import pandas as pd

In [17]:
df = pd.read_csv('/content/drive/MyDrive/hw_folder/supermarket_sales.csv')
df = pd.DataFrame(df)
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [18]:
branch_profit = df.groupby('Branch')['gross income'].sum().sort_values(ascending=False)
print(branch_profit)
print(f'\nНайприбутковішим філіалом є {branch_profit.idxmax()}.')

Branch
C    5265.1765
A    5057.1605
B    5057.0320
Name: gross income, dtype: float64

Найприбутковішим філіалом є C.

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [19]:
branch_profit_city = df.groupby('City')['gross income'].sum().sort_values(ascending=False)
print(branch_profit_city)
print(f'\nФіліал з найбільшим прибутком знаходиться в місті {branch_profit_city.idxmax()}')

City
Naypyitaw    5265.1765
Yangon       5057.1605
Mandalay     5057.0320
Name: gross income, dtype: float64

Філіал з найбільшим прибутком знаходиться в місті Naypyitaw

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [20]:
invoices_by_category = pd.pivot_table(df, index='Branch', columns='Product line', values='Invoice ID', aggfunc='count')
invoices_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [21]:
best_branch = invoices_by_category['Electronic accessories'].idxmax()
print(f'Найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" має філіал {best_branch}')

Найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" має філіал A

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

In [22]:
# 1. Чи впливає поєднання типу клієнта (Member/Normal) та статі на сумарний прибуток, середній чек та середню кількість товарів у чеку?
customer_analysis = df.groupby(['Customer type', 'Gender']).agg({'gross income': 'sum', 'Total': 'mean', 'Quantity': 'mean'})
customer_analysis

                      gross income       Total  Quantity
Customer type Gender
Member        Female     4197.4735  337.727753  5.716475
              Male       3622.6905  316.985419  5.387500
Normal        Female     3796.9515  332.233256  5.737500
              Male       3762.2535  305.047581  5.204633

Члени програми лояльності-жінки приносять найбільший сумарний прибуток.

In [23]:
# 2. В якому місті жінки приносять найбільший сумарний прибуток, а в якому — чоловіки?
gender_profit_city = df.groupby(['City', 'Gender'])['gross income'].sum().unstack()
print(gender_profit_city.round(2))

Gender      Female     Male
City
Mandalay   2520.40  2536.64
Naypyitaw  2937.40  2327.77
Yangon     2536.63  2520.53

Naypyitaw є лідером серед жіночої аудиторії саме вони є головним джерелом прибутку, варто розширити асортимент для них.

In [24]:
# 3. Чи залежить прибутковість і середній рейтинг від філіалу (Branch) та способу оплати (Payment)?
branch_payment_analysis = df.groupby(['Branch', 'Payment']).agg({'gross income':'sum','Total':'mean','Rating':'mean'})
branch_payment_analysis

                    gross income       Total    Rating
Branch Payment
A      Cash            1608.6310  307.102282  6.938182
       Credit card     1575.9405  318.218755  6.985577
       Ewallet         1872.5890  312.098167  7.138889
B      Cash            1682.8315  321.267832  6.998182
       Credit card     1778.3265  342.613362  6.760550
       Ewallet         1595.8740  296.578354  6.698230
C      Cash            2051.7075  347.466593  6.973387
       Credit card     1444.1650  309.463929  7.291837
       Ewallet         1769.3040  350.522491  6.986792

Для Branch A варто просувати оплату через Ewallet, бо вона дає найвищий дохід і середній рейтинг вище 7. Для Branch B – акцент на Credit card, для Branch C – на Cash.
Відстежувати задоволеність клієнтів (Rating) по способу оплати. Наприклад, у Branch B Ewallet показує найнижчий рейтинг, тож можна покращити сервіс при цьому способі оплати.